name: CEJ bolig tjekker

on:
  schedule:
    - cron: '*/5 * * * *'  # Kør hvert 5. minut
  workflow_dispatch:        # Gør det muligt at køre manuelt

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        FROM_PASSWORD: ${{ secrets.FROM_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python main.py
